language: python

cache: pip

python:
  - '2.7'
  - '3.6'

matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

install:
  - pip install -U pip setuptools flake8

script:
  - python setup.py test
  - flake8 disco/
